name: TheShrouded
version: "1.0.0"
main: zyx.araxia.shrouded.TheShrouded
api-version: "1.21"
description: A group minigame plugin
author: AriaC.

commands:
  "shrouded.register.lobby":
    description: Registers a region as a lobby
    usage: /shrouded.register.lobby <lobby_name> <x1> <y1> <z1> <x2> <y2> <z2> [world_name] [max_players]
    permission: shrouded.admin
    permission-message: You don't have permission to register lobbies.
  "shrouded.register.sign":
    description: Registers the sign you are looking at as an entry point for a lobby
    usage: /shrouded.register.sign <lobby_name>
    permission: shrouded.admin
    permission-message: You don't have permission to register signs.

permissions:
  shrouded.admin:
    description: Grants access to all Shrouded setup commands
    default: op
