name: TheShrouded
version: "1.0.0"
main: zyx.araxia.shrouded.TheShrouded
api-version: "1.21"
description: A group minigame plugin
author: AriaC.

commands:
  "shrouded.register.lobby":
    description: Registers a region as a lobby
    usage: /shrouded.register.lobby <lobby_name> <x1> <y1> <z1> <x2> <y2> <z2> [world_name] [max_players]
    permission: shrouded.admin
    permission-message: You don't have permission to register lobbies.
  "shrouded.register.sign":
    description: Registers the sign you are looking at as an entry point for a lobby
    usage: /shrouded.register.sign <lobby_name>
    permission: shrouded.admin
    permission-message: You don't have permission to register signs.
  "shrouded.register.arena":
    description: Registers a region as an arena
    usage: /shrouded.register.arena <arena_name> <x1> <y1> <z1> <x2> <y2> <z2> [world_name] [max_players]
    permission: shrouded.admin
    permission-message: You don't have permission to register arenas.
  "shrouded.lobby.arena":
    description: Links or unlinks an arena from a lobby's valid arenas list
    usage: /shrouded.lobby.arena <add|remove> <lobby_name> <arena_name>
    permission: shrouded.admin
    permission-message: You don't have permission to manage lobby arenas.
  "shrouded.lobby.countdown":
    description: Sets the countdown timer (in seconds) for a lobby
    usage: /shrouded.lobby.countdown <lobby_name> <seconds>
    permission: shrouded.admin
    permission-message: You don't have permission to manage lobby settings.

permissions:
  shrouded.admin:
    description: Grants access to all Shrouded setup commands
    default: op
